name: Build and push the docker image to the docker hub

on: push 
jobs:
  push_to_registry:
    name: Push Docker image to the docker hub 
    runs-on: ubuntu:latest
    steps:
      - name: check out the repo 
        uses: actions/checkout@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrest.DOCKERHUG_PASSWORD }}
      - name: Build and push the docker images 
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: chinnadurai31/git push -u origin main
